### ISSUE TITLE
Dependencies on local resources in MIMIC data extraction

### ISSUE THREAD

**Issue by treversec** [juhha1/Delirium_Prediction#1]
Thanks very much for sharing your code - we are trying to use this to reproduce the MIMIC-iii data extraction from your paper, but it looks as though two local resources are required for the code to run to conclusion:

ref_df = pd.read_excel('/shl_drive/shl_home/juhha/projects/Delirium/code_paper/data/MIMIC_ICU_reason_KRE.xlsx')
cci_ref = pd.read_csv('/shl_drive/shl_home/juhha/projects/Delirium/code_paper/data/comorbidity_code.csv')

Would it be possible to share these resources on GitHub?
Regards,
Trevor

**Comment by juhha1** [comment]
Thanks for your interest in this study.
The data was generated by my former colleague.
I will ask him if he still has the data and can share it.

**Comment by juhha1** [comment]
> Thanks very much for sharing your code - we are trying to use this to reproduce the MIMIC-iii data extraction from your paper, but it looks as though two local resources are required for the code to run to conclusion:
> 
> ref_df = pd.read_excel('/shl_drive/shl_home/juhha/projects/Delirium/code_paper/data/MIMIC_ICU_reason_KRE.xlsx') cci_ref = pd.read_csv('/shl_drive/shl_home/juhha/projects/Delirium/code_paper/data/comorbidity_code.csv')
> 
> Would it be possible to share these resources on GitHub? Regards, Trevor

Thanks for your interest in this study.
The data was generated by my former colleague.
I will ask him if he still has the data and can share it.

**Comment by treversec** [comment]
Thanks - do please let us know one way or the other.

**Comment by juhha1** [comment]
I forwarded this issue to my colleague and he said he will look for the data. But he is unsure that he still has the data or not. Also he mentioned that he used some package in R related to ICDs and comorbidity to make the data. If he contacts me back within 2 weeks, I will update you. If he does not, I will tell you what happened and close this issue.

**Comment by treversec** [comment]
Sounds good - thanks for pursuing this.

**Comment by juhha1** [comment]
I am sorry, it's been more than 2 weeks and I have not received any reply from my former colleague and other authors of the paper. 
To make it clear again, for this project, I was a data engineer and model developer, and I have no access or right to the data anymore...

If the data is still needed, I suggest contacting to other authors of the paper directly.
I will close this issue.
